import Head from "next/head";
import "modern-css-reset";
import styles from "../styles/Home.module.css";
import { Button } from "../components/Button";
import { Richtext } from "../components/Richtext";
import { Label } from "../components/Label";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Label>size="sm"</Label>
        <Button href="https://example.com" label="Yes!!!" size="sm" />
        <Label>size="md"</Label>
        <Button href="https://example.com" label="Yes!!!" size="md" />
        <Label>size="lg"</Label>
        <Button href="https://example.com" label="Yes!!!" size="lg" />
        <Label>size="md" / align="left"</Label>
        <Button
          href="https://example.com"
          label="Yes!!!"
          size="md"
          align="left"
        />
        <Label>size="md" / align="center"</Label>
        <Button
          href="https://example.com"
          label="Yes!!!"
          size="md"
          align="center"
        />
        <Label>size="md" / align="right"</Label>
        <Button
          href="https://example.com"
          label="Yes!!!"
          size="md"
          align="right"
        />
        <Label>Richtext</Label>
        <Richtext html={`
          <h2>Heading Lv2</h2>
          <p>The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. </p>
          <h3>Heading Lv3</h3>
          <p>The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. </p>
          <ul>
            <li>The quick brown fox jumps over the lazy dog. </li>
            <li>The quick brown fox jumps over the lazy dog. </li>
            <li>The quick brown fox jumps over the lazy dog. </li>
          </ul>
          <p>The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. </p>
          <h3>Heading Lv3</h3>
          <p>The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. </p>
          <p>The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. </p>
        `} />
        <Label>Richtext[dark]</Label>
        <Richtext dark html={`
          <h2>Heading Lv2</h2>
          <p>The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. </p>
          <h3>Heading Lv3</h3>
          <p>The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. </p>
          <ul>
            <li>The quick brown fox jumps over the lazy dog. </li>
            <li>The quick brown fox jumps over the lazy dog. </li>
            <li>The quick brown fox jumps over the lazy dog. </li>
          </ul>
          <p>The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. </p>
          <h3>Heading Lv3</h3>
          <p>The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. </p>
          <p>The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. </p>
        `} />
      </main>
    </div>
  );
}
